### ISSUE TITLE
NO LONGER MAINTAINED?  KILL IT

### ISSUE THREAD

**Issue by dschinkel** [db-migrate/pg#66]
If this project is no longer maintained, please say so.  Looks like the last commits were in 2019 and nobody has replied to any open issues in a long time.

**Comment by wzrdtales** [comment]
There were no commits b/c the pg driver pretty much just works. There was no apparent need, and it is actively used also as base driver for other pg based drivers.

Please refrain from being an a****le. This is open source not your free winter wonderland. If you desperately need features or support, come and pay some for it, OR, be decent and give something back to open source by **contributing** PRs and helping yourself others.  Just b/c no one answered your question which isn't even related to the driver, but just your lack of knowledge about the matter itself it doesn't mean it is dead. This is not free sausage land. And again.

You want desperate support? You **need** answers? Go find someone to help you, otherwise pay for it, but stop blaming the open source community for not pampering you.

**Comment by dschinkel** [comment]
It's hard to tell with no readme

**Comment by dschinkel** [comment]
![sausage](https://user-images.githubusercontent.com/338798/125157271-98e83780-e12f-11eb-9c8d-1825fa233e5c.jpeg)

**Comment by dschinkel** [comment]
https://giphy.com/gifs/drugs-weed-alice-in-wonderland-FdwDJ4l8RYVCU

**Comment by wzrdtales** [comment]
own fault for not being able to read the main repo and only looking at a driver.
